# Generated by Django 2.1.2 on 2018-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashedBlindedSecret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_blinded_secret', models.CharField(max_length=250)),
                ('is_signed', models.BooleanField(default=False)),
                ('signed_secret', models.CharField(blank=True, max_length=250)),
                ('unblinded_signed_secret', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
