# Generated by Django 2.1.2 on 2018-10-05 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashedblindedsecret',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
