# Generated by Django 2.1.2 on 2018-10-05 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0002_hashedblindedsecret_is_validated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashedblindedsecret',
            name='is_validated',
        ),
    ]
